{% set name = "pyribbit" %}
{% set version = "0.1.46" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fishbotics/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz 
  sha256: babcd34368bf83d8ae064209d1b72593275b5c9cb5aa69150c054c812af687c5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - freetype-py
    - imageio
    - networkx
    - numpy
    - pillow
    - pip
    - pyglet >=1.4.10
    - pyopengl >=3.1.0
    - python {{ python_min }}
    - scipy
    - six
    - trimesh
    - dataclasses
  run:
    - freetype-py
    - imageio
    - networkx
    - numpy
    - pillow
    - pyglet >=1.4.10
    - pyopengl >=3.1.0
    - python >={{ python_min }}
    - scipy
    - six
    - trimesh
    - dataclasses

test:
  imports:
    - pyribbit
    - pyribbit.platforms
  commands:
    - pip check
    - pytest -k "not (test_meshes or test_offscreen)" tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
    - examples

about:
  home: https://github.com/fishbotics/pyribbit
  summary: Easy-to-use Python renderer for 3D visualization
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
